Add all functionalities
andreeaiulia13/Assignment3 pull request #1
Opened 2021-05-06 11:50 UTC by andreeaiulia13

2021-05-06 12:25 UTC, vaneaclaudia requested changes

2021-05-06 12:25 UTC, vaneaclaudia commented on app/controllers/products_controller.rb
> + before_action :set_product, only:[:show, :edit, :update, :destroy]
please leave an empty space between `only:` and the array of values

2021-05-06 12:25 UTC, vaneaclaudia commented on app/controllers/products_controller.rb
> +    rescue => exception
It seems that you are not using `exception` here. Also, you will capture StandardError and all of its subtypes by not specifying an exact type of error to rescue. I think here you should capture the error thrown by Active Record (RecordInvalid)

2021-05-06 12:25 UTC, vaneaclaudia commented on app/controllers/products_controller.rb
> +    begin
you don't need to use `begin` keyword when you are doing the rescue for the whole implementation

2021-05-07 06:05 UTC, vaneaclaudia commented on app/controllers/products_controller.rb
> +
remove the empty line here. Also indentation looks a bit weird. `rescue` should be aligned with `def`

2021-05-07 06:05 UTC, vaneaclaudia approved these changes

2021-05-07 06:49 UTC, chioreandan approved these changes
Just 2 small changes and it is good to go 👍

2021-05-07 06:49 UTC, chioreandan commented on app/assets/stylesheets/dashboard.scss
> +}
Please add an empty line here, like you did on all the classes. :D

2021-05-07 06:49 UTC, chioreandan commented on app/assets/stylesheets/products.scss
> +.add_link {
```add-link```

2021-05-07 06:59 UTC, merged